# Generated by Django 4.0.3 on 2022-03-24 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(auto_created=True, unique=True)),
                ('org_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(auto_created=True, unique=True)),
                ('role_desc', models.CharField(choices=[('U', 'General User'), ('A', 'Admin User')], default='U', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(auto_created=True, unique=True)),
                ('tag_desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_title', models.CharField(max_length=100)),
                ('memo_create_date', models.DateField(verbose_name='date created')),
                ('memo_text', models.CharField(default='memo text', max_length=5000)),
                ('org', models.ManyToManyField(to='main_app.org')),
                ('tag', models.ManyToManyField(to='main_app.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-memo_create_date', 'memo_title'),
            },
        ),
    ]
