# Generated by Django 4.0.3 on 2022-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo_text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
