# Generated by Django 4.0.2 on 2022-03-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(auto_created=True, unique=True)),
                ('org_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(auto_created=True, unique=True)),
                ('role_desc', models.CharField(choices=[('U', 'General User'), ('A', 'Admin User')], default='U', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(auto_created=True, unique=True)),
                ('tag_desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='title',
            new_name='memo_title',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='user',
        ),
        migrations.AddField(
            model_name='memo',
            name='memo_create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='memo_text',
            field=models.CharField(default='missing', max_length=5000),
        ),
        migrations.AddField(
            model_name='memo',
            name='org_id',
            field=models.ForeignKey(default='missing', on_delete=django.db.models.deletion.CASCADE, to='main_app.org'),
        ),
        migrations.AddField(
            model_name='memo',
            name='tag_id',
            field=models.ForeignKey(default='missing', on_delete=django.db.models.deletion.CASCADE, to='main_app.tag'),
        ),
    ]
