# Generated by Django 4.0.3 on 2022-03-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_memo_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ('date',)},
        ),
    ]
