# Generated by Django 4.0.3 on 2022-03-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_org_memo_orgs_rename_tag_memo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
    ]
